### ISSUE TITLE
Directus dans le workflow pour faire la génération static site

### ISSUE THREAD

**Issue by kevinganthy** [gnth-web/test-sveltekit#3]
**Problématique :**

- Générer un site statique à partir d'un CMS
- Pouvoir modifier graphiquement le contenu d'un site
- Ne pas héberger le CMS

Fonctionnel grâce à ce job :
```yml
jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    
    steps:
      # Récupère le code du dépôt Github dans l'environnement du runner
      - name: Checkout
        uses: actions/checkout@v3
      - name: Directus serve
        run: |
          cd directus
          npm install
          npx directus start &
      - name: Svelte build
        run: |
          cd app
          npm install
          npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: ./app/build
          name: artifact
```

Upload sur GH pages :
```yml
  # Deploy on Github pages
  gh-pages:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}      
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3.0.4
        id: pages
      - name: Deploy GitHub Pages site
        id: deployment
        uses: actions/deploy-pages@v1.2.3
        with:
          artifact_name: artifact
```

Upload sur surge :
```yml
  # Deploy on surge.sh
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.1.1
        with:
          name: artifact
          path: ./build
      # Deploy to surge
      - name: Deploy
        run: |
          cd build
          tar -xvf artifact.tar
          rm artifact.tar
          npm install --global surge
          surge . --domain ${{ vars.SURGE_DEPLOY_URL }} --token ${{ secrets.SURGE_TOKEN }}
```

**Comment by kevinganthy** [comment]
Fonctionnel grâce à ce job :
```yml
jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    
    steps:
      # Récupère le code du dépôt Github dans l'environnement du runner
      - name: Checkout
        uses: actions/checkout@v3
      - name: Directus serve
        run: |
          cd directus
          npm install
          npx directus start &
      - name: Svelte build
        run: |
          cd app
          npm install
          npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.7
        with:
          path: ./app/build
          name: artifact
```
